[package]
name = "dal_spirits-proc"
version = "1.0.0"
edition = "2021"
publish = false
[lib]
proc-macro = true

[dependencies.quote]
version = "1"
default-features = false
[dependencies.syn]
version = "1"
features = ["proc-macro", "parsing", "derive", "printing"]
